spring.datasource.url=jdbc:postgresql://localhost:5433/ragdesk
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.jpa.show-sql=false
logging.level.org.springframework=INFO
logging.level.com.ragdesk=DEBUG
